### ISSUE TITLE
Switch to use versioneer for automated version numbers.

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pyca#10]
As of now the version is hardcoded at the setup.py.
With https://github.com/warner/python-versioneer we can grab the version string from the VCS and use it.
I can work on that if it is of interest.

**Comment by ZLLentz** [comment]
@hhslepicka I don't have the bandwidth to do `pyca` updates right now, but feel free to implement these if they make deployment easier for you. Apologies for forgetting about this, I bet we have a couple of inert tags right now where the builds have the wrong numbers attached.

**Comment by hhslepicka** [comment]
@ZLLentz I can totally do it if you think that it adds value to the tool! 👍 I would really like to collaborate and get more familiar with Pyca.
I will add a PR later this week.
